<div id="content">
    <div id="main" class="container">
        <div class="gallery">
            <ul class="main-slider">
                <li><img src="<?php echo $this->getSkinUrl('')?>images/index/slide01.jpg" alt=""></li>
                <li><img src="<?php echo $this->getSkinUrl('')?>images/index/slide02.jpg" alt=""></li>
                <li><img src="<?php echo $this->getSkinUrl('')?>images/index/slide03.jpg" alt=""></li>
            </ul>
        </div> <!-- gallery -->
    </div> <!-- main -->
</div> <!-- content -->