<!--<div id="footer" class="border">-->
<!--    --><?php //echo $this->__('Help Us to Keep Magento Healthy')?>
<!--    - <a href="http://www.magentocommerce.com/bug-tracking" onclick="this.target='_blank'">-->
<!--        <strong>--><?php //echo $this->__('Truong Long') ?><!--</strong>-->
<!--    </a>-->
<!--    --><?php //echo $this->__('(ver. %s)', Mage::getVersion()) ?>
<!--    --><?php //echo $this->getCopyright() ?><!--</address>-->
<!--</div>-->

<div id="footer">
    <div class="container">
        <div class="inner-footer cf">
            <div class="info-brand">
                <ul class="nav-footer cf">
                    <li class="item01"><a href="#">About</a></li>
                    <li class="item02"><a href="#">FAQ</a></li>
                    <li class="item03"><a href="#">Contact</a></li>
                </ul> <!-- nav-footer -->
                <p class="copyright">©2015 JUICE JUNKIE PTE LTD. ALL RIGHTS RESERVED.</p>
            </div> <!-- info-brand -->
            <div class="info-social">
                <div class="cf">
                    <ul class="social cf">
                        <li class="facebook"><a href="#">Facebook</a></li>
                        <li class="instagram"><a href="#">Instagram</a></li>
                    </ul> <!-- social -->
                    <div class="form-search">
                        <form action="">
                            <div class="box-search cf">
                                <input type="text" name="subscrible" value="Subscrible now" class="ipt-text">
                                <input type="submit" value="Go" class="ipt-submit">
                            </div> <!-- box-search -->
                        </form>
                    </div> <!-- form-search -->
                </div>
            </div> <!-- info-social -->
        </div> <!-- inner-footer -->
    </div> <!-- container -->
</div> <!-- footer -->