<div id="header">
    <div class="container">
        <div class="inner-header">
            <h1 id="logo">
                <a href="index.html"><img src="<?php echo $this->getSkinUrl('')?>images/index/logo_01.png" alt="Juice Junkie"></a>
            </h1>
            <?php echo $this->getChildHtml('topLinks') ?>
        </div> <!-- inner-header -->
    </div> <!-- container -->
</div> <!-- header -->
<?php echo $this->getChildHtml('topMenu') ?>