<!-- Lumos! :) -->
<!--<!DOCTYPE html>-->
<!--<html lang="en-GB">-->
<!--<head>-->
<?php //echo $this->getChildHtml('head') ?>
<!--</head>-->
<!---->
<!--<body>-->
<!--<div id="wrapper" class="border">-->
<!---->
<?php //echo $this->getChildHtml('header') ?>
<!---->
<!--    <div id="content" class="product">-->
<!--<php ////echo $this->getChildHtml('content') ?>-->
<!--    </div>-->
<!---->
<?php //echo $this->getChildHtml('footer') ?>
<!---->
<!--</div>-->
<!--</body>-->
<!--</html>-->
<!--truonglong 13/06-->
<!-- Lumos! :) -->
<!DOCTYPE html>
<html lang="en-GB">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>

<body>
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('content') ?>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
    <script src="js/vendor/jquery.bxslider.min.js"></script>
    <script src="js/common.js"></script>
    <?php echo $this->getChildHtml('footer') ?>
</body>
</html>