<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
?>

<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
    <div class="no-display">
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <div id="main-product-image"><?php echo $this->getChildHtml('media') ?></div>

        <div id="product-details">
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getChildHtml('addtocart') ?>
        </div>

        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>

        <?php if ($_product->getShortDescription()):?>
            <h2><?php echo $this->__('Quick Overview') ?></h2>
            <p class="quick-overview"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>
        <?php endif;?>

        <?php echo $this->getChildHtml('description') ?>
</form>
</div>